version: '3.8'

services:
  # ----------------------------------------
  # 2. Kafka Broker
  # ----------------------------------------
  kafka:
    image: docker.io/apache/kafka
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
#    environment:
      # Kafka's internal network address for other containers (using the service name)
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      # Advertised address for external access (localhost:9092)
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # ----------------------------------------
  # 3. Redis Server
  # ----------------------------------------
  redis:
    image: redis:alpine3.22
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    # Optional: Persist Redis data across container restarts
    # volumes:
    #   - redis_data:/data 

  # ----------------------------------------
  # 4. Python Scripts Container (The application logic)
  # ----------------------------------------
  python_app:
    build:
      context: .
      dockerfile: python-scripts/Dockerfile
    container_name: python_kafka_redis_app
    # The application starts after Kafka and Redis are ready
    depends_on:
      - kafka
      - redis
    environment:
      # Use the service names for inter-container communication
      KAFKA_BROKER: kafka:29092  # Internal Kafka port
      REDIS_HOST: redis         # Redis service name
    # Command can be adjusted based on which script you want to run (producer or consumer)
    command: python /app/kafka_producer.py
    # command: python /app/kafka_to_redis.py
    # command: python /app/read_from_redis.py

# volumes:
#   redis_data: {} # Define the volume if used above