version: '3.8'

services:
  # ----------------------------------------
  # 2. Kafka Broker
  # ----------------------------------------
  kafka:
    image: docker.io/apache/kafka
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
    # Defines the two ways Kafka can be reached
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092
      
      # Advertises the two addresses to clients
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      
      # Listener names for internal Docker networking
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT


  # ----------------------------------------
  # 3. Redis Server
  # ----------------------------------------
  redis:
    image: redis:alpine3.22
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    # Optional: Persist Redis data across container restarts
    # volumes:
    #   - redis_data:/data 

  # ----------------------------------------
  # 4. Python Scripts Container (The application logic)
  # ----------------------------------------
  python_app:
    image: data-simulator
    container_name: device-data-simulator
    # The application starts after Kafka and Redis are ready
    depends_on:
      - kafka
      - redis
    # Command can be adjusted based on which script you want to run (producer or consumer)
    #command: python3 /app/device-simulator.py
    command:  tail -f /dev/null
