name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ['self-hosted', 'Linux', 'X64']

    steps:
    - uses: actions/checkout@v4
    - name: Build backend
      run: podman build -t localhost/node-backend:$(date +%s)  node-backend/ 
    - name: Build Front-End
      run: podman build -t localhost/front-end:$(date +%s)  front-end/
    - name: Build Device Simulator
    - run: podman build -t localhost/device-simulator:$(date +%s) python-scripts/