name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ['self-hosted', 'Linux', 'X64']

    steps:
    - uses: actions/checkout@v4
    - name: Check for PWD
      run: |
        echo "current working directory is :"
        pwd
    - name: Build the Docker image
      run: podman build -t localhost/test-ci-cd-image:$(date +%s)  node-backend/ 